const iconMap = {
  's-home': 'House',
  's-grid': 'Grid',
  grid: 'Grid',
  home: 'House',
  setting: 'Setting',
  tools: 'Tools',
  tickets: 'Tickets',
  menu: 'Menu',
  's-custom': 'User',
  user: 'User',
  'user-solid': 'UserFilled',
  'data-analysis': 'DataAnalysis',
  's-operation': 'Operation',
  operation: 'Operation',
  monitor: 'Monitor',
  cpu: 'Cpu',
  folder: 'Folder',
  document: 'Document',
  search: 'Search',
  key: 'Key',
  filter: 'Filter',
  connection: 'Connection',
  collection: 'Collection',
  notebook: 'Notebook',
  clock: 'Clock',
  lock: 'Lock',
  's-order': 'Tickets',
  's-platform': 'Connection',
  coordinate: 'User',
  'message-solid': 'Message',
  's-cooperation': 'Tools',
  'notebook-2': 'Notebook',
  time: 'Clock',
  success: 'Monitor',
  's-data': 'Connection',
  's-opportunity': 'Filter'
}

export const menuIcon = icon => iconMap[icon] || 'Menu'
